services:
  frontend:
    build: 
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/node_modules
