services:
  frontend:
    build: 
      context: .
      dockerfile: packages/frontend/Dockerfile
    develop:
      watch:
        - path: ./packages/frontend/package.json
          action: rebuild
        - path: ./pnpm-lock.yaml
          action: rebuild
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/node_modules
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    develop:
      watch:
        - path: ./packages/backend/package.json
          action: rebuild
        - path: ./packages/backend/src/swaggger.json
          action: rebuild
        - path: ./pnpm-lock.yaml
          action: rebuild
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
      - /app/node_modules
