/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My TypeScript API
 * A local API documented via a static JSON file
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TaxonomyItem
} from './model';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Get all taxonomy items
 */
export type getApiResponse200 = {
  data: TaxonomyItem[]
  status: 200
}

export type getApiResponseSuccess = (getApiResponse200) & {
  headers: Headers;
};
;

export type getApiResponse = (getApiResponseSuccess)

export const getGetApiUrl = () => {




  return `http://localhost:3000/api`
}

export const getApi = async ( options?: RequestInit): Promise<getApiResponse> => {

  const res = await fetch(getGetApiUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiResponse
}





export const getGetApiQueryKey = () => {
    return [
    `http://localhost:3000/api`
    ] as const;
    }


export const getGetApiQueryOptions = <TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApi>>> = ({ signal }) => getApi({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiQueryResult = NonNullable<Awaited<ReturnType<typeof getApi>>>
export type GetApiQueryError = unknown


export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApi>>,
          TError,
          Awaited<ReturnType<typeof getApi>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApi>>,
          TError,
          Awaited<ReturnType<typeof getApi>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all taxonomy items
 */

export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
