/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Taxonomy API
 * API for browsing and searching taxonomy items
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiParams,
  TaxonomyResponse
} from './model';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Get paginated taxonomy items
 */
export type getApiResponse200 = {
  data: TaxonomyResponse
  status: 200
}

export type getApiResponseSuccess = (getApiResponse200) & {
  headers: Headers;
};
;

export type getApiResponse = (getApiResponseSuccess)

export const getGetApiUrl = (params?: GetApiParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api?${stringifiedParams}` : `http://localhost:3000/api`
}

export const getApi = async (params?: GetApiParams, options?: RequestInit): Promise<getApiResponse> => {

  const res = await fetch(getGetApiUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiResponse
}





export const getGetApiQueryKey = (params?: GetApiParams,) => {
    return [
    `http://localhost:3000/api`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiQueryOptions = <TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(params?: GetApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApi>>> = ({ signal }) => getApi(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiQueryResult = NonNullable<Awaited<ReturnType<typeof getApi>>>
export type GetApiQueryError = unknown


export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
 params: undefined |  GetApiParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApi>>,
          TError,
          Awaited<ReturnType<typeof getApi>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
 params?: GetApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApi>>,
          TError,
          Awaited<ReturnType<typeof getApi>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
 params?: GetApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get paginated taxonomy items
 */

export function useGetApi<TData = Awaited<ReturnType<typeof getApi>>, TError = unknown>(
 params?: GetApiParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApi>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
