/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My TypeScript API
 * A local API documented via a static JSON file
 * OpenAPI spec version: 1.0.0
 */

export type GetApiParams = {
/**
 * Page number (1-based)
 */
page?: number;
/**
 * Number of items per page
 */
offset?: number;
/**
 * Filter items by name (case-insensitive substring match)
 */
search?: string;
};
