/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Taxonomy API
 * API for browsing and searching taxonomy items
 * OpenAPI spec version: 1.0.0
 */

export type GetApiSortDir = typeof GetApiSortDir[keyof typeof GetApiSortDir];


export const GetApiSortDir = {
  asc: 'asc',
  desc: 'desc',
} as const;
