/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Taxonomy API
 * API for browsing and searching taxonomy items
 * OpenAPI spec version: 1.0.0
 */

export type GetApiParams = {
/**
 * Page number (1-based)
 */
page?: number;
/**
 * Number of items per page
 */
offset?: number;
/**
 * Filter items by name (case-insensitive substring match)
 */
search?: string;
/**
 * Artificial delay in milliseconds before responding
 */
delay?: number;
/**
 * Filter items to those whose name starts with this prefix
 */
parent?: string;
};
