/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Taxonomy API
 * API for browsing and searching taxonomy items
 * OpenAPI spec version: 1.0.0
 */
import type { TaxonomyTreeItemResponse } from './taxonomyTreeItemResponse';

export interface TaxonomyResponse {
  /** Name of the root/parent node */
  name?: string;
  items?: TaxonomyTreeItemResponse[];
  /** Total number of children under the root/parent node */
  total?: number;
}
