/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Taxonomy API
 * API for browsing and searching taxonomy items
 * OpenAPI spec version: 1.0.0
 */

export interface TaxonomyItem {
  name?: string;
  size?: number;
}
