/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My TypeScript API
 * A local API documented via a static JSON file
 * OpenAPI spec version: 1.0.0
 */
import type { TaxonomyItem } from './taxonomyItem';

export interface TaxonomyResponse {
  items?: TaxonomyItem[];
  total?: number;
}
